development:
  adapter: postgresql
  encoding: unicode
  database: yelp_clone_development
  pool: 5
  username: stevenkolock
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: yelp_clone_test
  pool: 5
  username: stevenkolock
  password: 
